services:
  - type: web
    name: petcare-backend
    env: docker
    dockerContext: petcare-backend
    dockerfilePath: petcare-backend/Dockerfile
    healthCheckPath: /
    healthCheckPolicy:
      initialDelaySeconds: 120
    cron:
      - path: /
        schedule: "*/14 * * * *"
