-- Esquema de base de datos para PetCare

-- 1. Usuarios
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    telefono VARCHAR(20),
    rol VARCHAR(30) NOT NULL, -- ADMINISTRADOR, VETERINARIO, ASISTENTE, DUENO
    activo BOOLEAN DEFAULT TRUE NOT NULL
);

-- 2. Dueños
CREATE TABLE IF NOT EXISTS duenos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    dni VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    telefono VARCHAR(20),
    direccion VARCHAR(200),
    usuario_id BIGINT REFERENCES usuarios(id),
    activo BOOLEAN DEFAULT TRUE NOT NULL
);

-- 3. Contactos de Emergencia
CREATE TABLE IF NOT EXISTS contactos_emergencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dueno_id BIGINT NOT NULL REFERENCES duenos(id),
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    relacion VARCHAR(50)
);

-- 4. Mascotas
CREATE TABLE IF NOT EXISTS mascotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    especie VARCHAR(50) NOT NULL,
    raza VARCHAR(50) NOT NULL,
    sexo VARCHAR(10) NOT NULL, -- MACHO, HEMBRA
    fecha_nacimiento DATE NOT NULL,
    microchip VARCHAR(50) UNIQUE,
    condicion_reproductiva VARCHAR(50), -- ESTERILIZADO, ENTERO, etc.
    alergias TEXT,
    enfermedades_cronicas TEXT,
    alertas_medicas TEXT,
    activo BOOLEAN DEFAULT TRUE NOT NULL
);

-- 5. Mascota Responsables (Relación N:M)
CREATE TABLE IF NOT EXISTS mascota_responsables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mascota_id BIGINT NOT NULL REFERENCES mascotas(id) ON DELETE CASCADE,
    dueno_id BIGINT NOT NULL REFERENCES duenos(id) ON DELETE CASCADE,
    es_principal BOOLEAN DEFAULT FALSE NOT NULL,
    relacion VARCHAR(50),
    CONSTRAINT uq_mascota_dueno UNIQUE (mascota_id, dueno_id)
);

-- 6. Historial de Transferencias
CREATE TABLE IF NOT EXISTS historial_transferencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mascota_id BIGINT NOT NULL REFERENCES mascotas(id),
    dueno_anterior_id BIGINT REFERENCES duenos(id),
    dueno_nuevo_id BIGINT NOT NULL REFERENCES duenos(id),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    motivo TEXT NOT NULL,
    usuario_responsable_id BIGINT NOT NULL REFERENCES usuarios(id)
);

-- 7. Servicios
CREATE TABLE IF NOT EXISTS servicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    duracion_minutos INT NOT NULL,
    costo_referencial DECIMAL(10,2) NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL
);

-- 8. Disponibilidad de Veterinarios
CREATE TABLE IF NOT EXISTS disponibilidad_veterinarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veterinario_id BIGINT NOT NULL REFERENCES usuarios(id),
    dia_semana INT NOT NULL, -- 1 = Lunes, 7 = Domingo
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL
);

-- 9. Bloqueos de Veterinarios
CREATE TABLE IF NOT EXISTS bloqueos_veterinarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veterinario_id BIGINT NOT NULL REFERENCES usuarios(id),
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    motivo VARCHAR(255)
);

-- 10. Citas
CREATE TABLE IF NOT EXISTS citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mascota_id BIGINT NOT NULL REFERENCES mascotas(id),
    veterinario_id BIGINT NOT NULL REFERENCES usuarios(id),
    servicio_id BIGINT NOT NULL REFERENCES servicios(id),
    fecha_hora TIMESTAMP NOT NULL,
    estado VARCHAR(30) NOT NULL, -- AGENDADA, CONFIRMADA, REPROGRAMADA, CANCELADA, ATENDIDA, NO_ASISTIO
    notas TEXT,
    creado_por BIGINT NOT NULL REFERENCES usuarios(id),
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 11. Sala de Espera
CREATE TABLE IF NOT EXISTS sala_espera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id BIGINT UNIQUE NOT NULL REFERENCES citas(id),
    mascota_id BIGINT NOT NULL REFERENCES mascotas(id),
    fecha_llegada TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado VARCHAR(30) NOT NULL, -- PENDIENTE, EN_ATENCION, ATENDIDO, NO_ASISTIO, REPROGRAMADO
    observaciones TEXT
);

-- 12. Triajes
CREATE TABLE IF NOT EXISTS triajes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id BIGINT UNIQUE NOT NULL REFERENCES citas(id),
    motivo_visita TEXT NOT NULL,
    nivel_urgencia VARCHAR(30) NOT NULL, -- RUTINARIA, PREFERENTE, URGENTE, EMERGENCIA
    signos_visibles TEXT,
    observaciones TEXT,
    peso DECIMAL(5,2),
    temperatura DECIMAL(4,1),
    frecuencia_cardiaca INT,
    frecuencia_respiratoria INT,
    asistente_id BIGINT NOT NULL REFERENCES usuarios(id),
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    actualizado_en TIMESTAMP
);

-- 13. Atenciones Clínicas
CREATE TABLE IF NOT EXISTS atenciones_clinicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id BIGINT REFERENCES citas(id),
    mascota_id BIGINT NOT NULL REFERENCES mascotas(id),
    veterinario_id BIGINT NOT NULL REFERENCES usuarios(id),
    triaje_id BIGINT REFERENCES triajes(id),
    motivo_consulta TEXT NOT NULL,
    sintomas TEXT,
    diagnostico TEXT NOT NULL,
    observaciones_clinicas TEXT,
    creado_por BIGINT NOT NULL REFERENCES usuarios(id),
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    actualizado_por BIGINT REFERENCES usuarios(id),
    actualizado_en TIMESTAMP
);

-- 14. Recetas Veterinarias
CREATE TABLE IF NOT EXISTS recetas_veterinarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atencion_id BIGINT UNIQUE NOT NULL REFERENCES atenciones_clinicas(id),
    indicaciones_generales TEXT,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 15. Detalles de Receta
CREATE TABLE IF NOT EXISTS receta_detalles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receta_id BIGINT NOT NULL REFERENCES recetas_veterinarias(id),
    medicamento VARCHAR(150) NOT NULL,
    dosis VARCHAR(100) NOT NULL,
    frecuencia VARCHAR(100) NOT NULL,
    duracion VARCHAR(100) NOT NULL,
    indicaciones TEXT
);

-- 16. Planes de Tratamiento
CREATE TABLE IF NOT EXISTS planes_tratamiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mascota_id BIGINT NOT NULL REFERENCES mascotas(id),
    atencion_id BIGINT REFERENCES atenciones_clinicas(id),
    descripcion TEXT NOT NULL,
    estado VARCHAR(30) NOT NULL, -- ACTIVO, COMPLETADO, SUSPENDIDO
    creado_por BIGINT NOT NULL REFERENCES usuarios(id),
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    actualizado_en TIMESTAMP
);

-- 17. Actividades de Plan
CREATE TABLE IF NOT EXISTS plan_actividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES planes_tratamiento(id),
    descripcion VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) NOT NULL, -- MEDICACION, CONTROL, ACTIVIDAD
    fecha_programada DATE NOT NULL,
    responsable_id BIGINT REFERENCES usuarios(id),
    estado VARCHAR(30) NOT NULL, -- PENDIENTE, REALIZADO, CANCELADO
    observaciones TEXT
);

-- 18. Consentimientos Informados
CREATE TABLE IF NOT EXISTS consentimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mascota_id BIGINT NOT NULL REFERENCES mascotas(id),
    dueno_id BIGINT NOT NULL REFERENCES duenos(id),
    procedimiento VARCHAR(150) NOT NULL,
    descripcion_riesgos TEXT,
    firmado BOOLEAN DEFAULT FALSE NOT NULL,
    fecha_firma TIMESTAMP,
    archivo_url VARCHAR(255),
    creado_por BIGINT NOT NULL REFERENCES usuarios(id),
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 19. Seguimientos Postconsulta
CREATE TABLE IF NOT EXISTS seguimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atencion_id BIGINT NOT NULL REFERENCES atenciones_clinicas(id),
    tipo VARCHAR(50) NOT NULL, -- LLAMADA, CONTROL_PRESENCIAL, REVISION_TRATAMIENTO
    fecha_programada DATE NOT NULL,
    fecha_realizada TIMESTAMP,
    estado VARCHAR(30) NOT NULL, -- PROGRAMADO, COMPLETADO, CANCELADO
    observaciones TEXT,
    responsable_id BIGINT NOT NULL REFERENCES usuarios(id),
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 20. Vacunaciones y Desparasitaciones
CREATE TABLE IF NOT EXISTS vacunaciones_desparasitaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mascota_id BIGINT NOT NULL REFERENCES mascotas(id),
    veterinario_id BIGINT NOT NULL REFERENCES usuarios(id),
    atencion_id BIGINT REFERENCES atenciones_clinicas(id),
    tipo VARCHAR(30) NOT NULL, -- VACUNA, DESPARASITACION
    nombre_producto VARCHAR(100) NOT NULL,
    dosis VARCHAR(50) NOT NULL,
    fecha_aplicacion DATE NOT NULL,
    proxima_dosis_fecha DATE,
    observaciones TEXT,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 21. Auditoría Clínica
CREATE TABLE IF NOT EXISTS auditoria_clinica (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modulo_afectado VARCHAR(100) NOT NULL,
    registro_id BIGINT NOT NULL,
    valor_anterior TEXT,
    valor_nuevo TEXT,
    motivo_cambio TEXT NOT NULL
);

-- 22. Token de Refresco
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT UNIQUE REFERENCES usuarios(id) ON DELETE CASCADE,
    token VARCHAR(255) UNIQUE NOT NULL,
    fecha_expiracion TIMESTAMP NOT NULL
);
